### PR TITLE
Update requirements.ms

### PR DESCRIPTION
**Pull request by liuzehaoleon**
-adding my name
-adding a paragraph in Introduction
-small indentation adjustment in name format

### CODE REVIEW

**Review by 0x1bi — APPROVED** [review]
LGTM

**Comment by 0x1bi** [comment]
Merge conflict present, I’ll fix it

**Comment by liuzehaoleon** [comment]
> LGTM

**Comment by liuzehaoleon** [comment]
> LGTM

**Comment by liuzehaoleon** [comment]
> Merge conflict present, I’ll fix it

Sorry, I did not saw the merged content. There is a guy write content in scope before which is no on the file yet.

**Comment by 0x1bi** [comment]
> > Merge conflict present, I’ll fix it
> 
> Sorry, I did not saw the merged content. There is a guy write content in scope before which is no on the file yet.

MR was resolved, don't worry.

**Pull request merged**
